<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

?>

<form class="card" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item"><a class="nav-link active" href="#modification" role="tab" data-bs-toggle="tab"><i class="fas fa-clipboard-check"></i> <?= $this->translate('Modification'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-bs-toggle="tab"><i class="fas fa-grip-horizontal"></i> <?= $this->translate('Configuration'); ?></a></li>
	</ul>

    <div class="tab-content pt-3">
        <div class="tab-pane fade show active" id="modification" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade <?= $index == 0 ? 'show active' : null; ?>" id="<?= sprintf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $modification); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Name')]); ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="tab-pane fade" id="configuration" role="tabpanel">
            <?= Element::hidden('modification[id]', $entity->getId()); ?>
            <?= Element::hidden('modification[car_id]', $entity->getCarId()); ?>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Price'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('modification[price]', $entity->getPrice(), ['class' => 'form-control', 'min' => '0', 'placeholder' => $this->translate('Modification price')]); ?>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$entity->getId(),
        'add' => ['Rentcar:Admin:CarModification@addAction', $entity->getCarId()],
        'edit' => 'Rentcar:Admin:CarModification@editAction',
        'save' => 'Rentcar:Admin:CarModification@saveAction',
        'cancel' => 'Rentcar:Admin:CarModification@gridAction'
    ]); ?>

</form>