<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="car" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#page" role="tab" data-toggle="tab"><i class="fas fa-car"></i> <?php $this->show('Car'); ?></a></li>
        <?php if (is_array($car)): ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#modification" role="tab" data-toggle="tab"><i class="fas fa-clipboard-check"></i> <?php $this->show('Modification'); ?> <small class="text-muted">(<?= count($modifications); ?>)</small></a></li>
        <?php endif; ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="fas fa-grip-horizontal"></i> <?php $this->show('Configuration'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#car-rental" role="tab" data-toggle="tab"><i class="fas fa-car-side"></i> <?php $this->show('Car rental'); ?></a></li>
    </ul>

    <div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <?php $entity = LanguageManager::findByLangId($language->getId(), $car); ?>

                <div class="tab-pane fade in <?= $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Page name'))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Capacity'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][capacity]', $language->getId()), $entity->getCapacity(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Transmission'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][transmission]', $language->getId()), $entity->getTransmission(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Safety'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][safety]', $language->getId()), $entity->getSafety(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Fuel'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][fuel]', $language->getId()), $entity->getFuel(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Airbags'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][airbags]', $language->getId()), $entity->getAirbags(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Interior'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][interior]', $language->getId()), $entity->getInterior(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Exterior'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][exterior]', $language->getId()), $entity->getExterior(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Features'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][features]', $language->getId()), $entity->getFeatures(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Options'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][options]', $language->getId()), $entity->getOptions(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="options">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'placeholder' => $this->translate('URL slug for this page. By default its taken from the name'))); ?>

                                    <span class="input-group-addon">
                                        <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12 control-label"><?php $this->show('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), array('class' => 'form-control')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), array('class' => 'form-control')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Page title'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                            </div>
                        </div>
                    </div>                    
                </div>
                <?php endforeach; ?>
            </div>
		</div>

        <?php if ($entity->getId()): ?>
        <div role="tabpanel" class="tab-pane" id="modification">
            <p>
                <a class="btn btn-primary" href="<?= $this->url('Rentcar:Admin:CarModification@addAction', $entity->getId()); ?>"><?php $this->show('Add new modification'); ?></a>
            </p>

            <h2 class="page-header"><?php $this->show('Modifications'); ?> <small>(<?= count($modifications); ?>)</small></h2>

            <?= $this->widget(new GridViewWidget($modifications, array(
                'tableClass' => 'table table-bordered',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'price',
                        'value' => function($row){
                            return number_format($row['price']);
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:CarModification@editAction', $row['id']),
                            $this->translate('Edit this modification')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:CarModification@deleteAction', $row['id']),
                            $this->translate('Remove this modification')
                        );
                    }
                )
            ))); ?>            
        </div>
        <?php endif; ?>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <?= Element::hidden('car[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
                <div class="col-lg-10">

                    <?php if (1): ?>
                    <p><img class="img-responsive" src="<?php echo $entity->getImageUrl('350x350'); ?>" /></p>

                    <?php else: ?>
                    <p><img data-image="preview" /></p>

                    <?php endif; ?>

                    <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                    <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Attached services'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('services[]', $services, $activeServiceIds, array('class' => 'form-control', 'multiple' => true, 'data-plugin' => 'chosen')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Sorting order'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[order]', $entity->getOrder(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Price'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[price]', $entity->getPrice(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Brand'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('car[brand_id]', $brands, $entity->getBrandId(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane" id="car-rental">
            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Quantity'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[qty]', $entity->getQty(), ['class' => 'form-control', 'min' => 0]); ?>
                </div>
            </div>
        </div>
	</div>

    <?php $this->loadPartial('actions', array(
        'new' => !$entity->getId(),
        'add' => 'Rentcar:Admin:Car@addAction',
        'edit' => 'Rentcar:Admin:Car@editAction',
        'save' => 'Rentcar:Admin:Car@saveAction',
        'options' => true,
        'cancel' => 'Rentcar:Admin:Car@indexAction'
    )); ?>

</form>
