<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

?>

<form class="card" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item"><a class="nav-link active" href="#page" role="tab" data-bs-toggle="tab"><i class="fas fa-car"></i> <?= $this->translate('Car'); ?></a></li>
        <?php if (is_array($car)): ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#modification" role="tab" data-bs-toggle="tab"><i class="fas fa-clipboard-check"></i> <?= $this->translate('Modification'); ?> <small class="text-muted">(<?= count($modifications); ?>)</small></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#car-gallery" role="tab" data-bs-toggle="tab"><i class="fas fa-camera-retro"></i> <?= $this->translate('Gallery'); ?> <small class="text-muted">(<?= count($gallery); ?>)</small></a></li>
        <?php endif; ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-bs-toggle="tab"><i class="fas fa-grip-horizontal"></i> <?= $this->translate('Configuration'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#car-rental" role="tab" data-bs-toggle="tab"><i class="fas fa-car-side"></i> <?= $this->translate('Car rental'); ?></a></li>
    </ul>

    <div class="tab-content pt-3">
		<div class="tab-pane fade show active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <?php $entity = LanguageManager::findByLangId($language->getId(), $car); ?>

                <div class="tab-pane fade <?= $index == 0 ? 'show active' : null; ?>" id="<?= sprintf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Page name')]); ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Capacity'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][capacity]', $language->getId()), $entity->getCapacity(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Transmission'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][transmission]', $language->getId()), $entity->getTransmission(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Safety'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][safety]', $language->getId()), $entity->getSafety(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Fuel'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][fuel]', $language->getId()), $entity->getFuel(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Airbags'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][airbags]', $language->getId()), $entity->getAirbags(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Interior'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][interior]', $language->getId()), $entity->getInterior(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Exterior'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][exterior]', $language->getId()), $entity->getExterior(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Features'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][features]', $language->getId()), $entity->getFeatures(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Options'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][options]', $language->getId()), $entity->getOptions(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="options">
                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), ['class' => 'form-control', 'placeholder' => $this->translate('URL slug for this page. By default its taken from the name')]); ?>

                                    <span class="input-group-text">
                                        <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="bi bi-arrow-clockwise" data-bs-toggle="tooltip" title="<?= $this->translate('Refresh the slug'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-12 col-form-label"><?= $this->translate('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), ['class' => 'form-select']); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), ['class' => 'form-select']); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'placeholder' => $this->translate('Page title')]); ?>
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), ['class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines')]); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), ['class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines')]); ?>
                            </div>
                        </div>
                    </div>                    
                </div>
                <?php endforeach; ?>
            </div>
		</div>

        <?php if ($entity->getId()): ?>
        <div role="tabpanel" class="tab-pane fade" id="modification">
            <p>
                <a class="btn btn-primary" href="<?= $this->url('Rentcar:Admin:CarModification@addAction', $entity->getId()); ?>"><?= $this->translate('Add new modification'); ?></a>
            </p>

            <h2 class="page-header"><?= $this->translate('Modifications'); ?> <small>(<?= count($modifications); ?>)</small></h2>

            <?= $this->widget(new GridViewWidget($modifications, [
                'tableClass' => 'table table-bordered',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'name'
                    ],

                    [
                        'column' => 'price',
                        'value' => function($row){
                            return number_format($row['price']);
                        }
                    ]
                ],

                'actions' => [
                    function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:CarModification@editAction', $row['id']),
                            $this->translate('Edit this modification')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:CarModification@deleteAction', $row['id']),
                            $this->translate('Remove this modification')
                        );
                    }
                ]
            ])); ?>
        </div>
        <?php endif; ?>

        <div role="tabpanel" class="tab-pane fade" id="car-gallery">
            <p>
                <a class="btn btn-primary btn-sm" href="<?= $this->url('Rentcar:Admin:CarGallery@addAction', $entity->getId()); ?>"><i class="fas fa-camera-retro"></i> <?= $this->translate('Upload new image'); ?></a>
            </p>

            <h2 class="page-header"><?= $this->translate('Gallery'); ?> <small>(<?= count($gallery); ?>)</small></h2>

            <?= $this->widget(new GridViewWidget($gallery, [
                'tableClass' => 'table table-bordered',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'image',
                        'value' => function($image){
                            return Element::image($image->getImageBag()->getUrl('original'), ['class' => 'img-fluid']);
                        }
                    ],

                    [
                        'column' => 'order'
                    ]
                ],

                'actions' => [
                    function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:CarGallery@editAction', $row['id']),
                            $this->translate('Edit this image')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:CarGallery@deleteAction', $row['id']),
                            $this->translate('Remove this image')
                        );
                    }
                ]
            ])); ?>
        </div>
        
        <div role="tabpanel" class="tab-pane fade" id="configuration">
            <?= Element::hidden('car[id]', $entity->getId()); ?>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Image'); ?></label>
                <div class="col-lg-10">

                    <?php if ($entity->getImage()): ?>
                    <p><img class="img-fluid" src="<?= $entity->getImageUrl('350x350'); ?>" /></p>

                    <?php else: ?>
                    <p><img data-image="preview" /></p>

                    <?php endif; ?>

                    <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="bi bi-image"></i> <?= $this->translate('Upload a file'); ?></a>
                    <?= Element::file('file', 'image/x-png, image/gif, image/jpeg', ['class' => 'd-none', 'data-plugin' => 'preview']); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-12 col-form-label"><?= $this->translate('Attached services'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('services[]', $services, $activeServiceIds, ['class' => 'form-select', 'multiple' => true, 'data-plugin' => 'chosen']); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-12 col-form-label"><?= $this->translate('Sorting order'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[order]', $entity->getOrder(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-12 col-form-label"><?= $this->translate('Price'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[price]', $entity->getPrice(), ['class' => 'form-control', 'step' => 'any']); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-12 col-form-label"><?= $this->translate('Brand'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('car[brand_id]', $brands, $entity->getBrandId(), ['class' => 'form-select']); ?>
                </div>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="car-rental">
            <div class="row mb-3">
                <label class="col-lg-12 col-form-label"><?= $this->translate('Quantity'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[qty]', $entity->getQty(), ['class' => 'form-control', 'min' => 0]); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-12 col-form-label"><?= $this->translate('Daily rent price'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[rent]', $entity->getRent(), ['class' => 'form-control', 'min' => 0, 'step' => 'any']); ?>
                </div>
            </div>
        </div>
	</div>

    <?php $this->loadPartial('actions', [
        'new' => !$entity->getId(),
        'add' => 'Rentcar:Admin:Car@addAction',
        'edit' => 'Rentcar:Admin:Car@editAction',
        'save' => 'Rentcar:Admin:Car@saveAction',
        'options' => true,
        'cancel' => 'Rentcar:Admin:Car@indexAction'
    ]); ?>

</form>