<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="car" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Page'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
    </ul>

    <div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <?php $entity = LanguageManager::findByLangId($language->getId(), $car); ?>

                <div class="tab-pane fade in <?= $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Page name'))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Capacity'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][capacity]', $language->getId()), $entity->getCapacity(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Transmission'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][transmission]', $language->getId()), $entity->getTransmission(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Safety'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][safety]', $language->getId()), $entity->getSafety(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Fuel'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][fuel]', $language->getId()), $entity->getFuel(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Airbags'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][airbags]', $language->getId()), $entity->getAirbags(), array('class' => 'form-control')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Interior'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][interior]', $language->getId()), $entity->getInterior(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Exterior'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][exterior]', $language->getId()), $entity->getExterior(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Features'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][features]', $language->getId()), $entity->getFeatures(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Options'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][options]', $language->getId()), $entity->getOptions(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                    <div class="options">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'placeholder' => $this->translate('URL slug for this page. By default its taken from the name'))); ?>

                                    <span class="input-group-addon">
                                        <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Page title'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                            </div>
                        </div>
                    </div>                    
                </div>
                <?php endforeach; ?>
            </div>
		</div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <?= Element::hidden('car[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
                <div class="col-lg-10">

                    <?php if (1): ?>
                    <p><img class="img-responsive" src="<?php echo $entity->getImageUrl('350x350'); ?>" /></p>

                    <?php else: ?>
                    <p><img data-image="preview" /></p>

                    <?php endif; ?>

                    <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                    <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Sorting order'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[order]', $entity->getOrder(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Price'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[price]', $entity->getPrice(), array('class' => 'form-control')); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Brand'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('car[brand_id]', $brands, $entity->getBrandId(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>
	</div>

    <?php $this->loadPartial('actions', array(
        'new' => !$entity->getId(),
        'add' => 'Rentcar:Admin:Car@addAction',
        'edit' => 'Rentcar:Admin:Car@editAction',
        'save' => 'Rentcar:Admin:Car@saveAction',
        'options' => true,
        'cancel' => 'Rentcar:Admin:Car@indexAction'
    )); ?>

</form>
