<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<form>
    <div class="btn-toolbar mb-3">
        <?php $this->loadPartial('menu', [
            'items' => [
                'Rentcar:Admin:Car@addAction' => 'Add new car',
                'Rentcar:Admin:Brand@indexAction' => 'Brands',
                'Rentcar:Admin:Lease@indexAction' => 'Car leasing',
                'Rentcar:Admin:RentService@indexAction' => 'Rent services',
                'Rentcar:Admin:Booking@statAction' => 'Statistic',
                'Rentcar:Admin:Booking@indexAction' => [
                    'caption' => 'Bookings',
                    'notifications' => $newBookings
                ]
            ],
            'actions' => [
                'data' => $cars,
                'delete' => 'Rentcar:Admin:Car@deleteAction'
            ]
        ]); ?>
    </div>

    <div class="card card-body">
        <?php $this->loadPartial('items-per-page', ['caption' => 'Cars']); ?>

        <h4><i class="bi bi-list-ul"></i> <?= $this->translate('Cars'); ?> (<?= count($cars); ?>)</h4>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($cars, [
                'tableClass' => 'table table-bordered table-sm',
                'pk' => 'id',
                'batch' => true,
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'image',
                        'value' => function($row){
                            return Element::image($row->getImageUrl('350x350'), ['class' => 'img-fluid col-5']);
                        }
                    ],

                    [
                        'column' => 'name'
                    ],

                    [
                        'column' => 'brand'
                    ],

                    [
                        'column' => 'order'
                    ]
                ],

                'actions' => [
                    function($row){
                        return Icon::view($row['url'], $this->translate('View this car on site'));
                    },

                    function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:Car@editAction', $row['id']),
                            $this->translate('Edit this car')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:Car@deleteAction', $row['id']),
                            $this->translate('Remove this car')
                        );
                    }
                ]
            ])); ?>

            <?php if (empty($cars)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No cars'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</form>