<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form>
    <div class="btn-toolbar">
        <?php $this->loadPartial('menu', array(
            'items' => array(
                'Rentcar:Admin:Car@addAction' => 'Add new car',
                'Rentcar:Admin:Brand@indexAction' => 'Brands',
                'Rentcar:Admin:Lease@indexAction' => 'Car leasing',
                'Rentcar:Admin:RentService@indexAction' => 'Rent services',
                'Rentcar:Admin:Booking@indexAction' => 'Bookings'
            ),
            'actions' => array(
                'data' => $cars,
                'delete' => 'Rentcar:Admin:Car@deleteAction'
            )
        )); ?>
    </div>

    <div class="card">
        <?php $this->loadPartial('items-per-page', array('caption' => 'Cars')); ?>

        <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Cars'); ?> (<?= count($cars); ?>)</h4>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($cars, array(
                'tableClass' => 'table table-bordered table-sm',
                'pk' => 'id',
                'batch' => true,
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'image',
                        'value' => function($row){
                            return Element::image($row->getImageUrl('350x350'), array('class' => 'img-fluid col-5'));
                        }
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'brand'
                    ),

                    array(
                        'column' => 'order'
                    )
                ),

                'actions' => array(
                    'view' => function($row){
                        return Icon::view($row['url'], $this->translate('View this car on site'));
                    },

                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:Car@editAction', $row['id']),
                            $this->translate('Edit this car')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:Car@deleteAction', $row['id']),
                            $this->translate('Remove this car')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($cars)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No cars'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</form>

