<p><?= $this->translate('Hello, there,'); ?></p>
<p><?= $this->translate('You have received a new order from the site.'); ?></p>
<p><?= $this->translate('Order information:'); ?></p>

<table>
    <tbody>
        <?php foreach ($client as $key => $value): ?>

        <?php if (!empty($value)): ?>
        <tr>
            <td><?= $this->translate($key); ?></td>
            <td><?= $value; ?></td>
        </tr>
        <?php endif; ?>

        <?php endforeach; ?>
    </tbody>
</table>

<p><?= $this->translate('Please enter administration panel and review this order manually. Thank you.'); ?></p>