<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

// Shared date format
$format = 'dd.mm.yyyy';

?>

<form class="card" data-group="lease" autocomplete="off">
    <?= Element::hidden('lease[id]', $lease->getId()); ?>

    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Owner'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[owner]', $lease->getOwner(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Model'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[model]', $lease->getModel(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Numberplate'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[numberplate]', $lease->getNumberplate(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Contract number'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[contract_number]', $lease->getContractNumber(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Apply date'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[apply_date]', $lease->getApplyDate(), ['class' => 'form-control', 'data-plugin' => 'datepicker', 'data-format' => $format]); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Run date'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[run_date]', $lease->getRunDate(), ['class' => 'form-control', 'data-plugin' => 'datepicker', 'data-format' => $format]); ?>
                </div>
            </div>
        </div>

        <div class="col-6">
            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Contract lease number'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[contract_lease_number]', $lease->getContractLeaseNumber(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Contract months'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('lease[period]', $this->translateArray($periods), $lease->getPeriod(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Contract status'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('lease[status]', $this->translateArray($statuses), $lease->getStatus(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('City applied'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[city_applied]', $lease->getCityApplied(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('City of owner'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('lease[city_owner]', $lease->getCityOwner(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Comment'); ?></label>
                <div class="col-lg-10">
                    <?= Element::textarea('lease[comment]', $lease->getComment(), ['class' => 'form-control']); ?>
                </div>
            </div>            
        </div>
    </div>
    
    <?php $this->loadPartial('actions', [
        'new' => !$lease->getId(),
        'add' => 'Rentcar:Admin:Lease@addAction',
        'edit' => 'Rentcar:Admin:Lease@editAction',
        'save' => 'Rentcar:Admin:Lease@saveAction',
        'cancel' => 'Rentcar:Admin:Lease@indexAction'
    ]); ?>

</form>