<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Rentcar\Collection\LeasePeriodCollection;
use Rentcar\Collection\StatusCollection;
use Cms\View\Icon;

$stCol = new LeasePeriodCollection();

?>

<form autocomplete="off">
    <div class="btn-toolbar mb-3">
        <div class="btn-group me-2">
            <?php $this->loadPartial('menu', [
                'items' => [
                    'Rentcar:Admin:Lease@addAction' => 'Add new contract'
                ],
                'actions' => [
                    'data' => $contracts,
                    'delete' => 'Rentcar:Admin:Lease@deleteAction'
                ]
            ]); ?>
        </div>

        <div class="btn-group me-2">
            <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i> <?= $this->translate('Filter'); ?></button>
        </div>
    </div>

    <div class="card card-body">
        <h4><i class="fab fa-accusoft"></i> <?= $this->translate('Contracts'); ?> (<?= count($contracts); ?>)</h4>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($contracts, [
                'tableClass' => 'table table-hover table-bordered',
                'batch' => true,
                'pk' => 'id',
                'rowAttributes' => [
                    'class' => function($row){
                        return $row['status'] == StatusCollection::STATUS_FINISHED ? 'table-success' : 'table-warning';
                    }
                ],
                'columns' => [
                    [
                        'column' => 'owner',
                        'filter' => true
                    ],

                    [
                        'column' => 'model',
                        'type' => 'select',
                        'filter' => $models
                    ],
                    
                    [
                        'column' => 'numberplate',
                        'filter' => true
                    ],
                    
                    [
                        'column' => 'contract_number',
                        'filter' => true
                    ],

                    [
                        'column' => 'period',
                        'translateable' => true,
                        'filter' => $this->translateArray($stCol->getAll()),
                        'type' => 'select',
                        'value' => function($row) use ($stCol){
                            return $stCol->findByKey($row['period']);
                        }
                    ]
                ],

                'actions' => [
                    function($row){
                        return Icon::details(
                            $this->url('Rentcar:Admin:Lease@viewAction', $row['id']),
                            $this->translate('View this contract')
                        );
                    },

                    function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:Lease@editAction', $row['id']),
                            $this->translate('Edit this contract')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:Lease@deleteAction', $row['id']),
                            $this->translate('Remove this contract')
                        );
                    }
                ]
            ])); ?>

            <?php if (empty($contracts)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No contracts'); ?></h2>
            </div>
            <?php endif; ?>
        </div>

        <?php $this->loadPartial('paginator'); ?>
    </div>
</form>