<?php

use Krystal\Widget\ListView\ListViewWidget;
use Rentcar\Collection\LeasePeriodCollection;
use Rentcar\Collection\StatusCollection;

?>

<div class="card card-body">
    <?= $this->widget(new ListViewWidget($lease, [
        'tableClass' => 'table table-hover table-bordered',
        'columns' => [
            [
                'column' => 'owner'
            ],

            [
                'column' => 'model'
            ],
            
            [
                'column' => 'numberplate'
            ],

            [
                'column' => 'contract_number'
            ],

            [
                'column' => 'apply_date'
            ],

            [
                'column' => 'run_date'
            ],

            [
                'column' => 'contract_lease_number'
            ],

            [
                'column' => 'period',
                'translate' => true,
                'value' => function($key, $value){
                    $lpCol = new LeasePeriodCollection();
                    return $lpCol->findByKey($value);
                }
            ],

            [
                'column' => 'status',
                'translate' => true,
                'value' => function($key, $value){
                    $stCol = new StatusCollection();
                    return $stCol->findByKey($value);
                }
            ],

            [
                'column' => 'city_applied'
            ],

            [
                'column' => 'city_owner'
            ],

            [
                'column' => 'comment'
            ]
        ]
    ])); ?>

</div>