<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="car" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Page'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
    </ul>

    <div class="tab-content">
		<div class="tab-pane fade in active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <?php $entity = LanguageManager::findByLangId($language->getId(), $car); ?>

                <div class="tab-pane fade in <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Page name'))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), array('data-wysiwyg' => 'true')); ?>
                        </div>
                    </div>

                </div>
                <?php endforeach; ?>
            </div>
		</div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <?= Element::hidden('car[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-12 control-label"><?php $this->show('Sorting order'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('car[order]', $entity->getOrder(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>
	</div>

    <?php $this->loadPartial('actions', array(
        'new' => !$entity->getId(),
        'add' => 'Rentcar:Admin:Car@addAction',
        'edit' => 'Rentcar:Admin:Car@editAction',
        'save' => 'Rentcar:Admin:Car@saveAction',
        'cancel' => 'Rentcar:Admin:Car@indexAction'
    )); ?>

</form>
