<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="image" autocomplete="off">
    <?= Element::hidden('image[id]', $image->getId()); ?>
    <?= Element::hidden('image[car_id]', $image->getCarId()); ?>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Order'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('image[order]', $image->getOrder(), ['class' => 'form-control']); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Image file'); ?></label>
        <div class="col-lg-10">
            <?php if ($image->getImage()): ?>
            <p><?= Element::image($image->getImageBag()->getUrl('original'), ['class' => 'img-fluid']); ?></p>
            <?php endif; ?>

            <?= Element::fileData('image[image]', $image->getImage(), 'image/*', ['class' => 'form-control']); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$image->getId(),
        'add' => 'Rentcar:Admin:CarGallery@addAction',
        'edit' => 'Rentcar:Admin:CarGallery@editAction',
        'save' => 'Rentcar:Admin:CarGallery@saveAction',
        'cancel' => 'Rentcar:Admin:Car@indexAction'
    ]); ?>
</form>