<?php

use Krystal\Form\Element;

?>

<form class="card card-body" autocomplete="off">
    <?= Element::hidden('brand[id]', $brand->getId()); ?>
    <?= Element::hidden('brand[icon]', $brand->getIcon()); ?>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('brand[name]', $brand->getName(), ['class' => 'form-control']); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-12 col-form-label"><?= $this->translate('Order'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::number('brand[order]', $brand->getOrder(), ['class' => 'form-control']); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Image'); ?></label>
        <div class="col-lg-10">

            <?php if ($brand->getIcon()): ?>
            <p><img class="img-fluid" src="<?= $brand->getImageUrl(); ?>" /></p>

            <?php else: ?>
            <p><img data-image="preview" /></p>

            <?php endif; ?>

            <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="bi bi-image"></i> <?= $this->translate('Upload a file'); ?></a>
            <?= Element::file('file', 'image/x-png, image/gif, image/jpeg', ['class' => 'd-none', 'data-plugin' => 'preview']); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$brand->getId(),
        'add' => 'Rentcar:Admin:Brand@addAction',
        'edit' => 'Rentcar:Admin:Brand@editAction',
        'save' => 'Rentcar:Admin:Brand@saveAction',
        'cancel' => 'Rentcar:Admin:Brand@indexAction'
    ]); ?>

</form>