<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<form>
    <div class="btn-toolbar mb-3">
        <a class="btn btn-primary" href="<?= $this->url('Rentcar:Admin:Brand@addAction'); ?>"><?= $this->translate('Add new brand'); ?></a>
    </div>

    <div class="card card-body">
        <h4><i class="bi bi-list-ul"></i> <?= $this->translate('Brands'); ?> (<?= count($brands); ?>)</h4>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($brands, [
                'tableClass' => 'table table-hover table-bordered',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'icon',
                        'value' => function($row){
                            return Element::image($row->getImageUrl(), ['class' => 'img-fluid']);
                        }
                    ],

                    [
                        'column' => 'name'
                    ],

                    [
                        'column' => 'order'
                    ]
                ],

                'actions' => [
                    function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:Brand@editAction', $row['id']),
                            $this->translate('Edit this brand')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:Brand@deleteAction', $row['id']),
                            $this->translate('Remove this brand')
                        );
                    }
                ]
            ])); ?>

            <?php if (empty($brands)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No brands'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</form>