<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form>
    <div class="btn-toolbar">
        <a class="btn btn-primary" href="<?= $this->url('Rentcar:Admin:Brand@addAction'); ?>"><?php $this->show('Add new brand'); ?></a>
    </div>

    <div class="card">
        <h4><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Brands'); ?> (<?= count($brands); ?>)</h4>

        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($brands, array(
                'tableClass' => 'table table-hover table-bordered',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'icon',
                        'value' => function($row){
                            return Element::image($row->getImageUrl(), array('class' => 'img-fluid'));
                        }
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'order'
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Rentcar:Admin:Brand@editAction', $row['id']),
                            $this->translate('Edit this brand')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Rentcar:Admin:Brand@deleteAction', $row['id']),
                            $this->translate('Remove this brand')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($brands)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No brands'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </div>
</form>

