<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;
use Rentcar\Collection\RentServiceUnitCollection;

?>

<div class="btn-toolbar mb-3">
    <div class="btn-group">
        <a class="btn btn-primary btn-sm" href="<?= $this->url('Rentcar:Admin:RentService@addAction'); ?>"><?= $this->translate('Add new service'); ?></a>
    </div>
</div>

<div class="card card-body">
    <h4 class="mb-4"><i class="fas fa-dolly"></i> <?= $this->translate('Rent services'); ?> <small class="text-muted">(<?= count($services); ?>)</small></h4>

    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($services, [
            'tableClass' => 'table table-bordered table-striped',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#',
                    'attributes' => [
                        'class' => 'text-muted text-center'
                    ]
                ],

                [
                    'column' => 'name',
                    'label' => 'Service name',
                    'attributes' => [
                        'class' => null
                    ],
                    'translateable' => true
                ],

                [
                    'column' => 'unit',
                    'translateable' => true,
                    'value' => function($row){
                        $rServUnitCol = new RentServiceUnitCollection();
                        return $rServUnitCol->findByKey($row['unit']);
                    },
                    'attributes' => [
                        'class' => function($row){
                            if ($row['price'] == 0){
                                return 'text-muted text-center';
                            } else {
                                return 'text-center';
                            }
                        }
                    ]
                ],
                
                [
                    'column' => 'price',
                    'translateable' => true,
                    'value' => function($row){
                        if ($row['price'] == 0){
                            return 'Free';
                        }

                        return $row['price'];
                    }
                ],

                [
                    'column' => 'order'
                ]
            ],

            'actions' => [
                function($row){
                    return Icon::edit(
                        $this->url('Rentcar:Admin:RentService@editAction', $row['id']),
                        $this->translate('Edit this service')
                    );
                },

                function($row){
                    return Icon::remove(
                        $this->url('Rentcar:Admin:RentService@deleteAction', $row['id']),
                        $this->translate('Remove this service')
                    );
                }
            ]
        ])); ?>
    </div>
</div>