<?php

use Krystal\Widget\ListView\ListViewWidget;
use Krystal\Widget\GridView\GridViewWidget;

?>

<div class="card">
    <h2><i class="fas fa-info-circle"></i> <?= $this->getBreadcrumbBag()->getLastName(); ?></h2>
    <hr />

    <div class="row">
        <div class="col-lg-6">
            <div class="text-center">
                <img src="<?= $car->getImageUrl('350x350'); ?>" class="img-fluid" />
                <p><?= $car->getName(); ?></p>
            </div>

            <?php if (!empty($services)): ?>
            <h2><?php $this->show('Attached services'); ?> <small class="text-muted">(<?= count($services); ?>)</small></h2>

            <?= $this->widget(new GridViewWidget($services, [
                'tableClass' => 'table table-bordered table-stripped',
                'columns' => [
                    ['column' => 'service'],
                    ['column' => 'price']
                ],
            ])); ?>
            <?php endif; ?>
        </div>

        <div class="col-lg-6">
            <?= $this->widget(new ListViewWidget($booking, [
                'columns' => [
                    ['column' => 'id', 'label' => '#'],
                    ['column' => 'name'],
                    ['column' => 'datetime'],
                    ['column' => 'name'],
                    ['column' => 'gender'],
                    ['column' => 'email'],
                    ['column' => 'pickup'],
                    ['column' => 'return'],
                    ['column' => 'checkin'],
                    ['column' => 'checkout'],
                    ['column' => 'status'],
                    ['column' => 'price'],
                    ['column' => 'comment']
                ]
            ])); ?>
        </div>
    </div>
</div>