<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="booking" autocomplete="off">
    <?= Element::hidden('booking[id]', $booking->getId()); ?>

    <div class="row">
        <div class="col-lg-6">
            <h2 class="mb-4 ml-3"><i class="fas fa-address-card"></i> <?php $this->show('Order details'); ?></h2>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Status'); ?></label>
                <div class="col-lg-10">
                    <?= Element::select('booking[status]', $this->translateArray($orderStatuses), $booking->getStatus(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Amount'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[amount]', $booking->getAmount(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Date and time'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[datetime]', $booking->getDatetime(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Comment'); ?></label>
                <div class="col-lg-10">
                    <?= Element::textarea('booking[comment]', $booking->getComment(), ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <h2 class="mb-4 ml-3"><i class="fas fa-user-tie"></i> <?php $this->show('Client details'); ?></h2>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Name'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[name]', $booking->getName(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Gender'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[gender]', $booking->getGender(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Email'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[email]', $booking->getEmail(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Phone'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[phone]', $booking->getPhone(), ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>

        <div class="col-lg-8">
            <h2 class="mb-4 ml-3"><i class="fas fa-car-side"></i> <?php $this->show('Pickup and return'); ?></h2>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Pickup'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[pickup]', $booking->getPickup(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Return'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[return]', $booking->getReturn(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Checkin'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[checkin]', $booking->getCheckin(), ['class' => 'form-control']); ?>
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Checkout'); ?></label>
                <div class="col-lg-10">
                    <?= Element::text('booking[checkout]', $booking->getCheckout(), ['class' => 'form-control']); ?>
                </div>
            </div>        
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$booking->getId(),
        'add' => 'Rentcar:Admin:Booking@addAction',
        'edit' => 'Rentcar:Admin:Booking@editAction',
        'save' => 'Rentcar:Admin:Booking@saveAction',
        'cancel' => 'Rentcar:Admin:Booking@indexAction'
    ]); ?>

</form>