<?php if (!empty($booking['status']) && !empty($booking['amount'])): ?>
<div class="container">
    <div class="row">
        <div class="col-3 bg-white p-4 me-3">
            <h2><i class="fas fa-user-check"></i></h2>

            <p><?= $this->translate('Order statuses'); ?></p>
            <p><?= $this->translate('Total orders'); ?>: <?= $booking['status']['total']; ?></p>

            <ul class="list-group">
              <?php foreach ($booking['status']['summary'] as $summary): ?>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= $this->translate($summary['status']); ?>
                <span class="badge bg-primary rounded-pill"><?= $summary['count']; ?></span>
              </li>
              <?php endforeach; ?>
            </ul>
        </div>

        <div class="col-4 bg-white p-4 me-3">
            <h2><i class="fas fa-money-bill-wave-alt"></i></h2>

            <p><?= $this->translate('Total amount (grouped by currencies)'); ?></p>

            <ul class="list-group">
              <?php foreach ($booking['amount'] as $price): ?>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= $price; ?>
              </li>
              <?php endforeach; ?>
            </ul>
        </div>

        <div class="col-4 bg-white p-4">
            <h2><i class="fas fa-car"></i></h2>

            <p><?= $this->translate('Car information'); ?></p>

            <ul class="list-group">
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= $this->translate('Total car models'); ?>
                <span class="badge bg-primary rounded-pill"><?= $car['models']; ?></span>
              </li>
              
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= $this->translate('Total quantity'); ?>
                <span class="badge bg-primary rounded-pill"><?= $car['qty']; ?></span>
              </li>
            </ul>
        </div>
    </div>
</div>
<?php else: ?>

<div class="card card-body">
    <h3><i class="fas fa-calendar-times"></i> <?= $this->translate('Statistic is empty'); ?></h3>
</div>

<?php endif; ?>